server:
  port: 4888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://${MYSQL_HOST:tb-mysql}:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
      username: root
      password: ${MYSQL_PWD}

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.dikar.entity

# 跨域设置 , 这样设置了还是不能跨域传 Cookie 不知道怎么回事
cors:
  allowed-origins: http://localhost:9527
  allowed-headers: Content-Type
  allowed-methods: GET,POST,OPTIONS
  allowed-credentials: true